{% set name = "macholib" %}
{% set version = "1.16.2" %}
{% set sha256 = "557bbfa1bb255c20e9abafe7ed6cd8046b48d9525db2f9b77d3122a63a2a8bf8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=2.7,<3|>=3.4
    - pip
    - setuptools
  run:
    - python >=2.7,<3|>=3.4
    - altgraph >=0.17

test:
  imports:
    - macholib
  commands:
    - python -m macholib find /tmp/

about:
  home: https://github.com/ronaldoussoren/macholib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Mach-O header analysis and editing
  description: |
    macholib can be used to analyze and edit Mach-O headers,
    the executable format used by Mac OS X.
  doc_url: https://macholib.readthedocs.io/en/latest/
  dev_url: https://github.com/ronaldoussoren/macholib

extra:
  recipe-maintainers:
    - rth
    - jakirkham
    - bkpoon
